# Generated by Django 4.2.13 on 2024-06-14 17:27

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    replaces = [("documents", "0001_initial"), ("documents", "0002_auto_20151226_1316")]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(blank=True, db_index=True, max_length=128)),
                ("title", models.CharField(blank=True, db_index=True, max_length=128)),
                ("content", models.TextField(db_index=True)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("sender", "title"),
            },
        ),
    ]
